apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-appofapps-lower
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: 
    targetRevision: feature/rmg
    path: overlays
  syncPolicy:
    automated:
      prune: true
      selfHeal: true